server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customer/**
        - id: telco-service
          uri: lb:http://TELCO-SERVICE
          predicates:
            - Path=/api/v1/telco/**
        - id: identity-service
          uri: lb:http://IDENTITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**